# must be unique in a given SonarQube instance
sonar.projectKey=rintio
# --- optional properties ---

# defaults to project key
sonar.projectName=rintio
# defaults to 'not provided'
#sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Defaults to .
sonar.sources=.
sonar.inclusions=**/*.js,**/*.vue, **/*.ts

sonar.host.url=http://codequality.rintio.com

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8sonar-scanner \
sonar.exclusions=node_modules/**, **/*.spec.js, **/*.spec.ts, eslint.config.js, i18n/**, nuxt.config.ts, mocks/**, vitest.**, plugins/**,**/addons/*, composables/pageMeta.ts

# Scan settings.
sonar.projectBaseDir=.
sonar.sourceEncoding=UTF-8

# Fail CI pipeline if Sonar fails.
sonar.qualitygate.wait=true

#sonar.testExecutionReportPaths=coverage/sonar-report.xml

#code coverage
sonar.javascript.lcov.reportPaths=./coverage/lcov.info
